package com.example.enesportfolio.core.model

data class PortfolioCopy(
    val skip: String,
    val navExperience: String,
    val navWork: String,
    val navNotes: String,
    val heroOverline: String,
    val heroRole: String,
    val heroLede: String,
    val downloadCv: String,
    val portraitCaption: String,
    val aboutTitle: String,
    val aboutBody: String,
    val nowLabel: String,
    val nowOne: String,
    val nowTwo: String,
    val nowThree: String,
    val expOverline: String,
    val expTitle: String,
    val j1When: String,
    val j1Role: String,
    val j1a: String,
    val j1b: String,
    val j1c: String,
    val j1d: String,
    val j1e: String,
    val j1f: String,
    val j1g: String,
    val j2When: String,
    val j2Role: String,
    val j2a: String,
    val j2b: String,
    val j2c: String,
    val j3When: String,
    val j3Company: String,
    val j3Role: String,
    val j3a: String,
    val stackOverline: String,
    val stackTitle: String,
    val stackLang: String,
    val stackAndroid: String,
    val stackArch: String,
    val stackSec: String,
    val stackCi: String,
    val eduOverline: String,
    val eduUniversity: String,
    val eduDegree: String,
    val eduWhen: String,
    val prodOverline: String,
    val prodTitle: String,
    val app1: String,
    val app2: String,
    val app3: String,
    val app4: String,
    val app5: String,
    val openPlay: String,
    val persOverline: String,
    val persTitle: String,
    val projSpotter: String,
    val projNews: String,
    val projPortfolio: String,
    val openRepo: String,
    val notesOverline: String,
    val notesTitle: String,
    val note1: String,
    val note2: String,
    val noteMoreWhen: String,
    val note3: String,
    val footerFocus: String,
)

data class SkillGroup(
    val title: String,
    val skills: List<String>,
)

data class NoteItem(
    val whenLabel: String,
    val title: String,
    val url: String,
)

data class ProjectItem(
    val index: String,
    val title: String,
    val description: String,
    val url: String,
    val linkLabel: String,
    val tags: List<String> = emptyList(),
)

data class GitHubShowcase(
    val title: String,
    val badge: String,
    val description: String,
    val cta: String,
    val tags: List<String>,
    val url: String,
)

data class PortfolioContent(
    val copy: PortfolioCopy,
    val skillGroups: List<SkillGroup>,
    val productionProjects: List<ProjectItem>,
    val personalProjects: List<ProjectItem>,
    val notes: List<NoteItem>,
    val github: GitHubShowcase,
)
